//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Abalone.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ABALONE_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_DLG_MENU               129
#define IDD_NEWGAME_DIALOG              130
#define IDI_DOWN_RIGHT_ARROW            131
#define IDI_DOWN_LEFT_ARROW             132
#define IDI_UP_LEFT_ARROW               133
#define IDI_UP_RIGHT_ARROW              134
#define IDI_RIGHT_ARROW                 135
#define IDI_LEFT_ARROW                  136
#define IDC_STATIC_PLAYER1              1001
#define IDC_STATIC_NAME1                1002
#define IDC_EDIT_NAME1                  1003
#define IDC_RADIO_HUMAN_PLAYER1         1004
#define IDC_RADIO_COMPUTER_MONTE_CARLO_PLAYER1 1005
#define IDC_RADIO_COMPUTER_ALPHA_BETA_PLAYER1 1006
#define IDC_RADIO_COMPUTER_EVALUATE_NEXT_MOVE_PLAYER1 1007
#define IDC_RADIO_COMPUTER_RANDOM_MOVES_PLAYER1 1008
#define IDC_STATIC_PLAYER2              1009
#define IDC_STATIC_NAME2                1010
#define IDC_EDIT_NAME2                  1011
#define IDC_RADIO_HUMAN_PLAYER2         1012
#define IDC_RADIO_COMPUTER_MONTE_CARLO_PLAYER2 1013
#define IDC_RADIO_COMPUTER_ALPHA_BETA_PLAYER2 1014
#define IDC_RADIO_COMPUTER_EVALUATE_NEXT_MOVE_PLAYER2 1015
#define IDC_RADIO_COMPUTER_RANDOM_MOVES_PLAYER2 1016
#define IDC_COMBO_START_FORMATION       1017
#define IDC_STATIC_START_FORMATION      1018
#define IDC_EDIT_NAME_PLAYER1           1019
#define IDC_EDIT_NAME_PLAYER2           1020
#define IDC_STATIC_PLAYERS_TURN         1021
#define IDC_BTN_MOVE_LEFT               1022
#define IDC_BTN_MOVE_RIGHT              1023
#define IDC_BTN_MOVE_UPLEFT             1024
#define IDC_BTN_MOVE_UPRIGHT            1025
#define IDC_BTN_MOVE_DOWNLEFT           1026
#define IDC_BTN_MOVE_DOWNRIGHT          1027
#define IDC_STATIC_LOST_BALLS           1028
#define IDC_EDIT_PLAYER1_SIM_GAMES      1029
#define IDC_EDIT_PLAYER1_NO_OF_TURNS_PER_SIM_GAME 1030
#define IDC_STATIC_PLAYER1_SIM_GAMES    1031
#define IDC_STATIC_PLAYER1_NO_OF_TURNS_PER_SIM_GAME 1032
#define IDC_EDIT_PLAYER2_SIM_GAMES      1033
#define IDC_EDIT_PLAYER2_NO_OF_TURNS_PER_SIM_GAME 1034
#define IDC_STATIC_PLAYER2_SIM_GAMES    1035
#define IDC_STATIC_PLAYER2_NO_OF_TURNS_PER_SIM_GAME 1036
#define IDC_EDIT_PLAYER1_TREE_DEPTH     1037
#define IDC_EDIT_PLAYER2_TREE_DEPTH     1038
#define IDC_STATIC_PLAYER1_TREE_DEPTH   1039
#define IDC_STATIC_PLAYER2_TREE_DEPTH   1040
#define IDC_STATIC_GROUP_PLAYER1_EVALUATION 1041
#define IDC_STATIC_GROUP_PLAYER2_EVALUATION 1042
#define IDC_STATIC_PLAYER1_EVALUATION   1043
#define IDC_STATIC_PLAYER2_EVALUATION   1044
#define IDC_EDIT_PLAYER1_EVALUATION     1045
#define IDC_EDIT_PLAYER2_EVALUATION     1046
#define IDC_STATIC_GROUP_PLAYER2_EVALUATION2 1047
#define IDC_STATIC_MAX_NO_OF_MOVES      1048
#define IDC_EDIT_MAX_NO_OF_MOVES        1049
#define ID_NEU_NEWGAME                  32771
#define ID_NEWGAME                      32772
#define ID_NEW_CLOSE                    32773
#define ID_CLOSE                        32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
